### ISSUE TITLE
update to work on Crystal 0.25

### ISSUE THREAD

**Issue by rishavs** [faustinoaq/sentry-run#1]
Currently using sentry is throwing exceptions;
````
Error in src/kemapi.cr:40: instantiating 'Sentry:Module#run(Sentry::ProcessRunner)'

    Sentry.run(opts) do
           ^~~

in lib/sentry-run/src/sentry-run.cr:18: instantiating 'Sentry::ProcessRunner#run()'

      process.run
              ^~~

in lib/sentry/src/sentry.cr:95: instantiating 'loop()'

      loop do
      ^~~~

in lib/sentry/src/sentry.cr:95: instantiating 'loop()'

      loop do
      ^~~~

in lib/sentry/src/sentry.cr:100: instantiating 'scan_files()'

        scan_files
        ^~~~~~~~~~

in lib/sentry/src/sentry.cr:77: instantiating 'get_timestamp(String)'

        timestamp = get_timestamp(file)
                    ^~~~~~~~~~~~~

in lib/sentry/src/sentry.cr:53: undefined method 'stat' for File:Class

      File.stat(file).mtime.to_s("%Y%m%d%H%M%S")
           ^~~~
````

**Comment by faustinoaq** [comment]
Depends on https://github.com/samueleaton/sentry/pull/27

As workaround try:

```yml
development_dependencies:
  sentry-run:
    github: faustinoaq/sentry-run
    branch: "crystal_0.25"
```

**Comment by faustinoaq** [comment]
https://github.com/samueleaton/sentry/pull/27 is Fixed :tada

However, sentry-run still depends on https://github.com/samueleaton/sentry/issues/29

**Comment by faustinoaq** [comment]
Hi @rishavs I just released sentry-run 0.3.0, see: https://github.com/faustinoaq/sentry-run/releases/tag/v0.3.0 :tada:
